/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import Logic.Logic;
import Entities.Automovil;
import java.time.LocalDateTime;
/**
 *
 * @author yeric
 */
public class Entrada_Parqueo extends javax.swing.JFrame {
    Logic L = new Logic();
    Automovil v = new Automovil();
    /**
     * Creates new form Entrada_Parqueo
     */
    public Entrada_Parqueo() {
        initComponents();
        Seleccion_Gas.setVisible(false);
        Input_Marca.setVisible(false);
        Input_Modelo.setVisible(false);
        Label_marca.setVisible(false);
        Label_modelo.setVisible(false);
        jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
        jRadioButton3.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        Botones_Camion = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Seleccion_Vehiculo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        Input_PlacaRegistro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Input_Servicio = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        Seleccion_Gas = new javax.swing.JComboBox<>();
        Input_Marca = new javax.swing.JTextField();
        Input_Modelo = new javax.swing.JTextField();
        Label_marca = new javax.swing.JLabel();
        Label_modelo = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        imagenEntrada = new javax.swing.JLabel();
        jOptionPane1 = new javax.swing.JOptionPane();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Botones_Camion.add(jRadioButton1);
        Botones_Camion.add(jRadioButton2);
        Botones_Camion.add(jRadioButton3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 492));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(450, 492));
        jPanel1.setLayout(null);

        Seleccion_Vehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Automovil", "Motocicleta", "Camion" }));
        Seleccion_Vehiculo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Seleccion_VehiculoItemStateChanged(evt);
            }
        });
        Seleccion_Vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seleccion_VehiculoActionPerformed(evt);
            }
        });
        jPanel1.add(Seleccion_Vehiculo);
        Seleccion_Vehiculo.setBounds(20, 140, 140, 30);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Swis721 Blk BT", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Tipo De Vehiculo");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 110, 140, 20);

        Input_PlacaRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_PlacaRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(Input_PlacaRegistro);
        Input_PlacaRegistro.setBounds(10, 220, 190, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Swis721 Blk BT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setOpaque(true);
        jLabel2.setText("Placa del vehiculo");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 190, 150, 22);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Swis721 Blk BT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setOpaque(true);
        jLabel3.setText("Tipo de Servicio");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 270, 130, 18);

        Input_Servicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Por Dia", "Por Hora" }));
        Input_Servicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_ServicioActionPerformed(evt);
            }
        });
        jPanel1.add(Input_Servicio);
        Input_Servicio.setBounds(50, 290, 100, 26);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(153, 153, 153));
        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 370, 140, 27);

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setForeground(new java.awt.Color(153, 153, 153));
        jToggleButton1.setText("Regresar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(20, 410, 116, 27);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("MENU REGISTRO DE VEHICULO");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 40, 320, 29);

        Seleccion_Gas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gasolina", "Diesel", "Electrico" }));
        Seleccion_Gas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seleccion_GasActionPerformed(evt);
            }
        });
        jPanel1.add(Seleccion_Gas);
        Seleccion_Gas.setBounds(280, 260, 90, 26);
        jPanel1.add(Input_Marca);
        Input_Marca.setBounds(200, 330, 150, 26);

        Input_Modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_ModeloActionPerformed(evt);
            }
        });
        jPanel1.add(Input_Modelo);
        Input_Modelo.setBounds(210, 380, 130, 26);

        Label_marca.setFont(new java.awt.Font("Swis721 Blk BT", 0, 12)); // NOI18N
        Label_marca.setText("Ingrese la marca del auto");
        Label_marca.setOpaque(true);
        jPanel1.add(Label_marca);
        Label_marca.setBounds(190, 310, 170, 20);

        Label_modelo.setFont(new java.awt.Font("Swis721 Blk BT", 1, 12)); // NOI18N
        Label_modelo.setText("Ingrese el modelo de su auto");
        Label_modelo.setOpaque(true);
        jPanel1.add(Label_modelo);
        Label_modelo.setBounds(180, 360, 210, 15);

        jRadioButton1.setText("2 Ejes");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(260, 180, 80, 21);

        jRadioButton2.setText("3 a 4 Ejes");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(260, 200, 72, 21);

        jRadioButton3.setText("6 Ejes o mas");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(260, 220, 100, 21);

        imagenEntrada.setFont(new java.awt.Font("Georgia Pro", 1, 12)); // NOI18N
        imagenEntrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagenEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ParqueoImagen.jpg"))); // NOI18N
        imagenEntrada.setText("jLabel1");
        imagenEntrada.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imagenEntrada.setMaximumSize(new java.awt.Dimension(450, 492));
        imagenEntrada.setMinimumSize(new java.awt.Dimension(450, 492));
        jPanel1.add(imagenEntrada);
        imagenEntrada.setBounds(0, 0, 430, 450);

        jOptionPane1.setMessage("La palaca del vahiculo debe contener 3 letras y 3 numeros (abc123)!");
        jPanel1.add(jOptionPane1);
        jOptionPane1.setBounds(100, 380, 230, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Seleccion_VehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seleccion_VehiculoActionPerformed
        if(!Input_PlacaRegistro.getText().isEmpty()){
         if(Seleccion_Vehiculo.getSelectedItem().toString().equalsIgnoreCase("Automovil"))
         {

         }}
        
    }//GEN-LAST:event_Seleccion_VehiculoActionPerformed

    // Boton para regresar al menu principal
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

        this.dispose(); // elimina de la vista la ventana actual
        new GUI.mainMenu().setVisible(true); // genera la vista de la ventana del menu principal
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    // Boton para registrar el vehiculo y regresar al menu principal
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!Input_PlacaRegistro.getText().isEmpty()) // validacion de espacio vacio.
        {
           if(L.ValidacionInputAlphaNum(Input_PlacaRegistro.getText())) // llamado de la funcion de validacion
           {
           
           }
           else{jOptionPane1.showMessageDialog(this,"Debe ingresar una placa valida! (abc123)");}
        }else
        {
            jOptionPane1.showMessageDialog(this,"El ingreso de placa es de caracter obligatorio!");
        }  
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Input_PlacaRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_PlacaRegistroActionPerformed
       
    }//GEN-LAST:event_Input_PlacaRegistroActionPerformed

    private void Seleccion_VehiculoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Seleccion_VehiculoItemStateChanged
        
        String op = Seleccion_Vehiculo.getSelectedItem().toString();
        switch(op)
        {
            case "Automovil" -> 
            {
                Seleccion_Gas.setVisible(true);
                Input_Marca.setVisible(true);
                Input_Modelo.setVisible(true);
                Label_marca.setVisible(true);
                Label_modelo.setVisible(true);
                jRadioButton1.setVisible(false);
                jRadioButton2.setVisible(false);
                jRadioButton3.setVisible(false);
            }
            case "Motocicleta" -> 
            {
                Label_marca.setText("Ingrese el cilindraje de su moto");
                Input_Marca.setVisible(true);
                Label_marca.setVisible(true);
                Seleccion_Gas.setVisible(false);
                Label_modelo.setVisible(false);
                Input_Modelo.setVisible(false);
                jRadioButton1.setVisible(false);
                jRadioButton2.setVisible(false);
                jRadioButton3.setVisible(false);
            }
            case "Camion" -> 
            {
                Label_marca.setText("Ingrese la capacidad del camion");
                Input_Marca.setVisible(true);
                Label_marca.setVisible(true);
                Seleccion_Gas.setVisible(false);
                Label_modelo.setVisible(false);
                Input_Modelo.setVisible(false);
                jRadioButton1.setVisible(true);
                jRadioButton2.setVisible(true);
                jRadioButton3.setVisible(true);
            }
        }
        
    }//GEN-LAST:event_Seleccion_VehiculoItemStateChanged

    private void Input_ServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_ServicioActionPerformed
        // TODO add your handling code here:
         if(!Input_PlacaRegistro.getText().isEmpty()){
            Input_Servicio.getSelectedItem().toString();}
    }//GEN-LAST:event_Input_ServicioActionPerformed

    private void Input_ModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_ModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_ModeloActionPerformed

    private void Seleccion_GasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seleccion_GasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Seleccion_GasActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Registro(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrada_Parqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrada_Parqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrada_Parqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrada_Parqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entrada_Parqueo().setVisible(true);
            }
        });}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Botones_Camion;
    private javax.swing.JTextField Input_Marca;
    private javax.swing.JTextField Input_Modelo;
    private javax.swing.JTextField Input_PlacaRegistro;
    private javax.swing.JComboBox<String> Input_Servicio;
    private javax.swing.JLabel Label_marca;
    private javax.swing.JLabel Label_modelo;
    private javax.swing.JComboBox<String> Seleccion_Gas;
    private javax.swing.JComboBox<String> Seleccion_Vehiculo;
    private javax.swing.JLabel imagenEntrada;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
