/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import Logic.Logic;
/**
 *
 * @author yeric
 */
public class mainMenu extends javax.swing.JFrame {
Logic L = new Logic();
    /**
     * Creates new form mainMenu
     */
    public mainMenu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Boton_Registro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Boton_Salida = new javax.swing.JButton();
        Boton_Reportes = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        Boton_Registro.setBackground(new java.awt.Color(255, 255, 255));
        Boton_Registro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Boton_Registro.setForeground(new java.awt.Color(153, 153, 153));
        Boton_Registro.setText("Registrar Vehiculo");
        Boton_Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_RegistroActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Registro);
        Boton_Registro.setBounds(120, 70, 150, 27);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        jLabel2.setText("Servicio Parqueo");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 10, 180, 23);

        Boton_Salida.setBackground(new java.awt.Color(255, 255, 255));
        Boton_Salida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Boton_Salida.setForeground(new java.awt.Color(153, 153, 153));
        Boton_Salida.setText("Salida De Vehiculo");
        Boton_Salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_SalidaActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Salida);
        Boton_Salida.setBounds(120, 110, 150, 27);

        Boton_Reportes.setBackground(new java.awt.Color(255, 255, 255));
        Boton_Reportes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Boton_Reportes.setForeground(new java.awt.Color(153, 153, 153));
        Boton_Reportes.setText("Reporte");
        Boton_Reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_ReportesActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Reportes);
        Boton_Reportes.setBounds(150, 200, 79, 27);

        jButton1.setText("Ver Vehiculos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 160, 110, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ParqueoImagen.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_RegistroActionPerformed
        // TODO add your handling code here:
        GUI.Entrada_Parqueo.Registro();
        this.dispose();

    }//GEN-LAST:event_Boton_RegistroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GUI.Mostrar_Vehiculos.MostrarVehiculos();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Boton_SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_SalidaActionPerformed
        
        GUI.Salida_Vehiculos.Salida();
        this.dispose();
    }//GEN-LAST:event_Boton_SalidaActionPerformed

    private void Boton_ReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_ReportesActionPerformed
        GUI.MenuReportes.reportes();
        this.dispose();
    }//GEN-LAST:event_Boton_ReportesActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Registro;
    private javax.swing.JButton Boton_Reportes;
    private javax.swing.JButton Boton_Salida;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
