/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import Logic.LogicReportes;
public class MenuReportes extends javax.swing.JFrame {
LogicReportes R = new LogicReportes();
    /**
     * Creates new form MenuReportes
     */
    public MenuReportes() {
        initComponents();
        setLocationRelativeTo(null);
        R.leerAtendidos();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Boton_Horas = new javax.swing.JButton();
        Boton_Pagos = new javax.swing.JButton();
        Boton_Porcentaje = new javax.swing.JButton();
        Boton_Atendidos = new javax.swing.JButton();
        Boton_Regresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        OptionPane_Caracteristica1 = new javax.swing.JOptionPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Swis721 Blk BT", 1, 14)); // NOI18N
        jLabel2.setText("SUB MENU DE REPORTES");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 10, 200, 18);

        Boton_Horas.setText("Horas Totales");
        Boton_Horas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_HorasActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Horas);
        Boton_Horas.setBounds(150, 60, 150, 27);

        Boton_Pagos.setText("Pagos totales");
        Boton_Pagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_PagosActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Pagos);
        Boton_Pagos.setBounds(150, 100, 150, 27);

        Boton_Porcentaje.setText("Porcentaje Uso");
        Boton_Porcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_PorcentajeActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Porcentaje);
        Boton_Porcentaje.setBounds(150, 140, 150, 27);

        Boton_Atendidos.setText("Vehiculos Atendidos");
        Boton_Atendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_AtendidosActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Atendidos);
        Boton_Atendidos.setBounds(150, 180, 150, 27);

        Boton_Regresar.setText("Regresar");
        Boton_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_RegresarActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Regresar);
        Boton_Regresar.setBounds(10, 260, 100, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ParqueoImagen.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 660, 310);
        jPanel1.add(OptionPane_Caracteristica1);
        OptionPane_Caracteristica1.setBounds(210, 230, 210, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_HorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_HorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_HorasActionPerformed

    private void Boton_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_RegresarActionPerformed
        this.dispose();
        new GUI.mainMenu().setVisible(true);
    }//GEN-LAST:event_Boton_RegresarActionPerformed

    private void Boton_AtendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_AtendidosActionPerformed
        OptionPane_Caracteristica1.showMessageDialog(this,R.VehiculosAtendidos());
    }//GEN-LAST:event_Boton_AtendidosActionPerformed

    private void Boton_PorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_PorcentajeActionPerformed
        OptionPane_Caracteristica1.showMessageDialog(this,R.PorcentajeUso());
    }//GEN-LAST:event_Boton_PorcentajeActionPerformed

    private void Boton_PagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_PagosActionPerformed
        OptionPane_Caracteristica1.showMessageDialog(this,R.PagosTotales());
    }//GEN-LAST:event_Boton_PagosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void reportes() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Atendidos;
    private javax.swing.JButton Boton_Horas;
    private javax.swing.JButton Boton_Pagos;
    private javax.swing.JButton Boton_Porcentaje;
    private javax.swing.JButton Boton_Regresar;
    private javax.swing.JOptionPane OptionPane_Caracteristica1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
