
package GUI;
import Logic.Logic_Validaciones;
import Logic.Logic_Salida;

public class Salida_Vehiculos extends javax.swing.JFrame {
    Logic_Validaciones v = new Logic_Validaciones();
    Logic_Salida s = new Logic_Salida();
    /**
     * Creates new form Salida_Vehiculos
     */
    public Salida_Vehiculos() {
        initComponents();
        setLocationRelativeTo(null);
        this.setSize(420, 380); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label_placa = new javax.swing.JLabel();
        Input_placa = new javax.swing.JTextField();
        Buscar_Vehiculo = new javax.swing.JButton();
        Salida_Vehiculo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jOptionPane1 = new javax.swing.JOptionPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));

        jPanel1.setPreferredSize(new java.awt.Dimension(420, 380));
        jPanel1.setLayout(null);

        Label_placa.setFont(new java.awt.Font("Swis721 Blk BT", 1, 12)); // NOI18N
        Label_placa.setText("Ingrese la placa de su vehiculo:");
        jPanel1.add(Label_placa);
        Label_placa.setBounds(0, 20, 220, 20);

        Input_placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_placaActionPerformed(evt);
            }
        });
        jPanel1.add(Input_placa);
        Input_placa.setBounds(220, 20, 160, 26);

        Buscar_Vehiculo.setText("Buscar");
        Buscar_Vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar_VehiculoActionPerformed(evt);
            }
        });
        jPanel1.add(Buscar_Vehiculo);
        Buscar_Vehiculo.setBounds(260, 50, 76, 27);

        Salida_Vehiculo.setText("Registrar Salida");
        jPanel1.add(Salida_Vehiculo);
        Salida_Vehiculo.setBounds(270, 310, 120, 27);

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 310, 90, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ParqueoImagen.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(420, 380));
        jLabel1.setMaximumSize(new java.awt.Dimension(400, 300));

        jPanel1.setLayout(null);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -1, 420, 350);
        jPanel1.add(jOptionPane1);
        jOptionPane1.setBounds(80, 160, 262, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Input_placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_placaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_placaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new GUI.mainMenu().setVisible(true); // genera la vista de la ventana del menu principal
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Buscar_VehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar_VehiculoActionPerformed
        if(v.ValidacionInputAlphaNum(Input_placa.getText()))
        {
            s.Existencia_Actualizacion(Input_placa.getText());
            String mensaje = s.factura();
            jOptionPane1.showMessageDialog(this,mensaje);
        }
    }//GEN-LAST:event_Buscar_VehiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Salida() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salida_Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salida_Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salida_Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salida_Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salida_Vehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar_Vehiculo;
    private javax.swing.JTextField Input_placa;
    private javax.swing.JLabel Label_placa;
    private javax.swing.JButton Salida_Vehiculo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
