
package GUI;
import Logic.Logic_Validaciones;
import Logic.Logic_Salida;

public class Salida_Vehiculos extends javax.swing.JFrame {
    Logic_Validaciones v = new Logic_Validaciones();
    Logic_Salida s = new Logic_Salida();
    /**
     * Creates new form Salida_Vehiculos
     */
    public Salida_Vehiculos() {
        initComponents();
        setLocationRelativeTo(null);
        this.setSize(420, 380);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label_placa = new javax.swing.JLabel();
        Input_placa = new javax.swing.JTextField();
        Buscar_Vehiculo = new javax.swing.JButton();
        Salida_Vehiculo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Label_MostrarPlaca = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Label_MostrarServicio = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Label_HoraEntrada = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Label_HoraSalida = new javax.swing.JLabel();
        Mostrar_TiempoEnParqueo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Mostrar_PagoTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jOptionPane1 = new javax.swing.JOptionPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));

        jPanel1.setPreferredSize(new java.awt.Dimension(420, 380));
        jPanel1.setLayout(null);

        Label_placa.setFont(new java.awt.Font("Swis721 Blk BT", 1, 12)); // NOI18N
        Label_placa.setText("Ingrese la placa de su vehiculo:");
        jPanel1.add(Label_placa);
        Label_placa.setBounds(0, 20, 220, 20);

        Input_placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_placaActionPerformed(evt);
            }
        });
        jPanel1.add(Input_placa);
        Input_placa.setBounds(220, 20, 160, 26);

        Buscar_Vehiculo.setText("Buscar");
        Buscar_Vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar_VehiculoActionPerformed(evt);
            }
        });
        jPanel1.add(Buscar_Vehiculo);
        Buscar_Vehiculo.setBounds(260, 50, 76, 27);

        Salida_Vehiculo.setText("Registrar Salida");
        Salida_Vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salida_VehiculoActionPerformed(evt);
            }
        });
        jPanel1.add(Salida_Vehiculo);
        Salida_Vehiculo.setBounds(270, 310, 120, 27);

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 310, 90, 27);

        jLabel2.setText("Placa:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 90, 50, 16);
        jPanel1.add(Label_MostrarPlaca);
        Label_MostrarPlaca.setBounds(60, 90, 80, 20);

        jLabel3.setText("Servicio:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 140, 50, 16);
        jPanel1.add(Label_MostrarServicio);
        Label_MostrarServicio.setBounds(60, 140, 70, 20);

        jLabel4.setText("Hora Entrada:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 180, 80, 16);
        jPanel1.add(Label_HoraEntrada);
        Label_HoraEntrada.setBounds(90, 180, 130, 20);

        jLabel5.setText("Hora Salida:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 220, 70, 16);
        jPanel1.add(Label_HoraSalida);
        Label_HoraSalida.setBounds(90, 220, 140, 20);
        jPanel1.add(Mostrar_TiempoEnParqueo);
        Mostrar_TiempoEnParqueo.setBounds(130, 270, 60, 20);

        jLabel6.setText("Tiempo en parqueo:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 270, 110, 16);

        jLabel7.setText("Pago Total:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(220, 280, 60, 16);
        jPanel1.add(Mostrar_PagoTotal);
        Mostrar_PagoTotal.setBounds(290, 280, 90, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ParqueoImagen.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(420, 380));
        jLabel1.setMaximumSize(new java.awt.Dimension(400, 300));

        jPanel1.setLayout(null);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -1, 410, 360);
        jPanel1.add(jOptionPane1);
        jOptionPane1.setBounds(80, 160, 262, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Input_placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_placaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_placaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new GUI.mainMenu().setVisible(true); // genera la vista de la ventana del menu principal
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Buscar_VehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar_VehiculoActionPerformed
        s.TomarDatos();
        Label_MostrarPlaca.setText(Input_placa.getText());
        Label_MostrarServicio.setText(s.TipoServicio);
        Label_HoraEntrada.setText(s.entrada);
        Label_HoraSalida.setText(s.Salida);
        Mostrar_PagoTotal.setText(s.pagoTarifa);
        //Mostrar_TiempoEnParqueo.setText(s.Tiempoparqueo);
        if(v.ValidacionInputAlphaNum(Input_placa.getText()))
        {
            if(s.Existencia_Actualizacion(Input_placa.getText())){
            jOptionPane1.showMessageDialog(this,"Vehiculo encontrado!");
            if(s.AplicarDescuento())
            {
                jOptionPane1.showMessageDialog(this,"Felicidades has estado al menos 8 horas por lo que aplica un 10% de descuento!");
            }
            }else{jOptionPane1.showMessageDialog(this,"Vehiculo no encontrado!");}
        }
    }//GEN-LAST:event_Buscar_VehiculoActionPerformed

    private void Salida_VehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salida_VehiculoActionPerformed
        s.BorrarVehiculo(Input_placa.getText());
        this.dispose();
        new GUI.mainMenu().setVisible(true);
    }//GEN-LAST:event_Salida_VehiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Salida() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salida_Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salida_Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salida_Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salida_Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salida_Vehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar_Vehiculo;
    private javax.swing.JTextField Input_placa;
    private javax.swing.JLabel Label_HoraEntrada;
    private javax.swing.JLabel Label_HoraSalida;
    private javax.swing.JLabel Label_MostrarPlaca;
    private javax.swing.JLabel Label_MostrarServicio;
    private javax.swing.JLabel Label_placa;
    private javax.swing.JLabel Mostrar_PagoTotal;
    private javax.swing.JLabel Mostrar_TiempoEnParqueo;
    private javax.swing.JButton Salida_Vehiculo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
